### ISSUE TITLE
Does not work with CrystalDiskInfo special editions

### ISSUE THREAD

**Issue by Wiesmak** [Lifailon/CrystalDisk-Cli#1]
CrystalDiskInfo comes in various editions featuring some original characters (Shizuku, Aoi, Kurei Kei), all of which have different executable name (DiskInfo64S.exe, DiskInfo64A.exe, DiskInfo64K.exe).
The script should detect the installed edition and use the corresponding executable.
It would also be nice to test-path before start-process and gracefully inform the user that CrystalDiskInfo is not installed, rather than throwing file not found errors.

**Comment by Lifailon** [comment]
I currently do not support PowerShell projects, you can make changes and I will accept your changes via `Pull requests`.

**Comment by Wiesmak** [comment]
Done.
I have no idea how to use nuget though, so plese make an updated package.

**Comment by Lifailon** [comment]
Thanks for your contribution! 

> I have no idea how to use nuget though, so plese make an updated package.

The package has been updated in nuget.
